# Generated by Django 4.2.28 on 2026-02-12 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='catalog_cat_active_924593_idx',
            old_name='catalog_ca_active_0d8ae0_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_categor_61c0a7_idx',
            old_name='catalog_pr_category_0ff31e_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_name_f603c0_idx',
            old_name='catalog_pr_name_ee01f8_idx',
        ),
        migrations.RenameIndex(
            model_name='productbarcode',
            new_name='catalog_pro_ean_84c116_idx',
            old_name='catalog_pr_ean_4c5e16_idx',
        ),
        migrations.RenameIndex(
            model_name='productprice',
            new_name='catalog_pro_product_4068cc_idx',
            old_name='catalog_pr_product_37ed90_idx',
        ),
    ]
