# Generated by Django 4.2.28 on 2026-02-12 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeconfig',
            options={'verbose_name': 'Store Config'},
        ),
        migrations.RenameIndex(
            model_name='cashmove',
            new_name='sales_cashm_session_22ecd6_idx',
            old_name='sales_cas_session_35b7f3_idx',
        ),
        migrations.RenameIndex(
            model_name='cashsession',
            new_name='sales_cashs_status_e73353_idx',
            old_name='sales_cas_status_8b5b46_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='sales_order_status_5a79ce_idx',
            old_name='sales_ord_status_1d22ab_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='sales_order_created_8a4d37_idx',
            old_name='sales_ord_created_90260f_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='sales_order_order_i_3655c0_idx',
            old_name='sales_ord_order_i_6a4d7f_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='sales_payme_order_i_929708_idx',
            old_name='sales_pay_order_i_6b3f32_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='sales_payme_created_0df64f_idx',
            old_name='sales_pay_created_0d8c84_idx',
        ),
    ]
