# Generated by Django 4.2.28 on 2026-03-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_rename_sales_order_busines_b2e5b4_idx_sales_order_busines_69e71a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfig',
            name='pix_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
