# Generated by Django 4.2.28 on 2026-02-12 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='kitchenticket',
            new_name='kitchen_kit_status_154069_idx',
            old_name='kitchen_ki_status_68f8f0_idx',
        ),
    ]
