# Generated by Django 4.2.28 on 2026-03-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('preparo', 'Em preparo'), ('despachado', 'Saindo para entrega'), ('entregue', 'Entregue')], default='novo', max_length=20),
        ),
    ]
