# Generated by Django 4.2.28 on 2026-02-12 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_customer_profile_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='loyalty_cus_phone_510dd1_idx',
            old_name='loyalty_cu_phone_3e5a5a_idx',
        ),
        migrations.RenameIndex(
            model_name='loyaltymove',
            new_name='loyalty_loy_custome_8da727_idx',
            old_name='loyalty_lo_customer_168399_idx',
        ),
    ]
