# Generated by Django 4.2.28 on 2026-03-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_catalog_ca_active_0d8ae0_idx_catalog_cat_active_924593_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
