# Generated by Django 4.2.28 on 2026-02-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameIndex(
            model_name='rolepermission',
            new_name='accounts_ro_role_id_5b564a_idx',
            old_name='accounts_ro_role_id_26d6a0_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_email_74c8d6_idx',
            old_name='accounts_us_email_7f6d33_idx',
        ),
        migrations.RenameIndex(
            model_name='userrole',
            new_name='accounts_us_user_id_5c3bd8_idx',
            old_name='accounts_us_user_id_1b02c9_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
    ]
