# Generated by Django 4.2.28 on 2026-02-12 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_entity_8edb54_idx',
            old_name='audit_aud_entity_4c9d06_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_created_2c1626_idx',
            old_name='audit_aud_created_f9a2a8_idx',
        ),
    ]
