# Generated by Django 4.2.28 on 2026-02-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_storeconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfig',
            name='category_images',
            field=models.JSONField(default=dict),
        ),
    ]
