# Generated by Django 4.2.28 on 2026-03-25 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0005_order_daily_sequence'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='sales_order_busines_69e71a_idx',
            old_name='sales_order_busines_b2e5b4_idx',
        ),
        migrations.AddField(
            model_name='cashsession',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='reconciliation_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
