# Generated by Django 4.2.28 on 2026-03-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_storeconfig_pix_key'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'closed_at'], name='sales_order_status_1c53f1_idx'),
        ),
    ]
