# Generated by Django 4.2.28 on 2026-04-02 13:01

import apps.sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_storeconfig_delivery_fee_settings'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deliveryordermeta',
            new_name='sales_deliv_status_d14794_idx',
            old_name='sales_deliv_status_93ef2b_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryordermeta',
            new_name='sales_deliv_source_46ba68_idx',
            old_name='sales_deliv_source_528ed3_idx',
        ),
        migrations.AlterField(
            model_name='deliveryordermeta',
            name='source',
            field=models.CharField(choices=[('pdv', 'PDV'), ('web', 'Web'), ('whatsapp', 'WhatsApp')], default='whatsapp', max_length=20),
        ),
        migrations.AlterField(
            model_name='storeconfig',
            name='delivery_fee_rules',
            field=models.JSONField(default=apps.sales.models.default_delivery_fee_rules),
        ),
    ]
